### PR TITLE
OTWO-5284 Add updated_at field to etags table

### PR DESCRIPTION
**Pull request by Priya5**

### CODE REVIEW

**Comment by PDegenPortnoy** [comment]
This looks good. One notes that we do not need a script to populate existing records in the table because this will be a new table in production.

**Comment by sig-krasnick** [comment]
I had an issue last week running the migration on a current PG database.  Were you able to run this against PG or only MySQL?

**Comment by Priya5** [comment]
I ran it on PG.
```
➜  github-mirror git:(OTWO-5284) ✗ sequel -m lib/ghtorrent/migrations postgres://postgres@localhost/ght_development
Adding table etags
```

**Comment by notalex** [comment]
In order to avoid extra merge complexity, I am going to include this change in my work in branch *etag*.

**Pull request closed without merging**
